name: feed-search-engine
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-resources-uris:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Use js sparql query
        run: node -e 'import("https://raw.githubusercontent.com/sherlock-iremus/sherlock-sparql-queries/main/src/queries/getResources.js").then(query => console.log(query.getResources()));'
 
      - name: Store the get-resources-uris SPARQL query JS file
        run: curl https://raw.githubusercontent.com/sherlock-iremus/sherlock-sparql-queries/main/src/queries/getResources.js > tmp.sparql

      - name: Parse JS file to have sparql query
        run: sed '1d; $d' tmp.sparql > tmp_as_sparql.sparql
        
      - name: remove newlines to match with curl 
        run: tr '\n' ' ' < tmp_as_sparql.sparql > query.sparql

      - name: sparql query to get resources-uri
        run: |
            curl --location --request POST 'https://data-iremus.huma-num.fr/sparql' \
              --header 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode "query=$(cat query.sparql)" > resources-uri.json

      - name: Get identities of each resource
        run: cat resources-uri.json
