name: feed-search-engine
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-resources-uris:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Store the get-resources-uris SPARQL query JS file
        run: curl https://raw.githubusercontent.com/sherlock-iremus/sherlock-sparql-queries/main/src/queries/getResources.js > tmp.sparql

      - name: Parse JS file to have sparql query
        run: sed '1d; $d' tmp.sparql > get_uris.sparql
        
      - name: query sparql endpoint to get identities
        run: cat get_uris.sparql
