name: feed-search-engine
on:
  workflow_dispatch:

jobs:
  get-resources-uris:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#
#      - name: download js sparql query
#        run: wget https://raw.githubusercontent.com/sherlock-iremus/sherlock-sparql-queries/main/src/queries/getResources.js
#
#      - name: Use js sparql query
#        run: |
#          node -e '
#          const https = require("https");
#          const fs = require("fs");
#          const sparqlQuery = require("./getResources.js");
#          const options = {
#            hostname: "data-iremus.huma-num.fr",
#            path: "/sparql",
#            method: "POST",
#            headers: {
#              "Content-Type": "application/x-www-form-urlencoded",
#              "Accept": "application/json",
#            },
#          };
#          const req = https.request(options, (res) => {
#            let data = [];
#          
#            res.on("data", (chunk) => {
#              data.push(chunk);
#            });
#          
#            res.on("end", () => {
#              fs.writeFileSync("res.json",JSON.stringify(JSON.parse(Buffer.concat(data).toString())))
#            });
#          });
#          
#          req.on("error", (e) => {
#            console.error(e);
#          });
#          
#          req.write(`query=${encodeURIComponent(sparqlQuery())}`);
#          req.end();
#          '
#
#      - name: try a simple ssh 
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan -t rsa data-iremus.huma-num.fr >> ~/.ssh/known_hosts
#          ssh -i ~/.ssh/id_rsa tbottini@data-iremus.huma-num.fr ls 
#        env:
#          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: execute command on prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PWD }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            whoami
            ls -la

#      - name: cache resource uris on prod
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          port: 22
#          source: "./res.json"
#          target: elastic-search
